create database LocVideo;

USE [LocVideo] 
GO

CREATE TABLE UTILISATEUR (
UTI_ID INT NOT NULL IDENTITY,
UTI_LOGIN varchar (200) null,
UTI_MDP varchar (200) null,
UTI_NOM varchar (200) null,
UTI_PRENOM varchar (200) null,
UTI_EMAIL varchar (200) null,
UTI_ISADMIN bit,
CONSTRAINT PK_UTILISATEUR PRIMARY KEY(UTI_ID)
);

CREATE TABLE CATEGORIE (
CAT_ID INT NOT NULL IDENTITY,
CAT_IDMERE INT,
CAT_NOM varchar (200) null, 
CONSTRAINT PK_CATEGORIE PRIMARY KEY(CAT_ID),
CONSTRAINT FK_CATEGORIE_CATEGORIE FOREIGN KEY(CAT_IDMERE) REFERENCES CATEGORIE(CAT_ID)
);

CREATE TABLE VIDEO (
VID_ID INT NOT NULL IDENTITY,
VID_NOM varchar (200) null, 
VID_DESCRIPTION varchar (200) null, 
VID_NOTEMOYEN FLOAT, 
VID_DATECRE DATE null, 
VID_USERCRE varchar (200) null, 
VID_IDCATEGORIE INT,
CONSTRAINT PK_VIDEO PRIMARY KEY(VID_ID),
CONSTRAINT FK_VIDEO_CATEGORIE FOREIGN KEY(VID_IDCATEGORIE) REFERENCES CATEGORIE(CAT_ID)
);

CREATE TABLE LOCATION(
LOC_ID INT NOT NULL IDENTITY,
LOC_DATELOC DATE,
LOC_DATELIMITERETOUR DATE,
LOC_IDUTILISATEUR INT,
LOC_IDVIDEO INT,
CONSTRAINT PK_LOCATION PRIMARY KEY(LOC_ID),
CONSTRAINT FK_LOCATION_UTILISATEUR FOREIGN KEY(LOC_IDUTILISATEUR) REFERENCES UTILISATEUR(UTI_ID),
CONSTRAINT FK_LOCATION_VIDEO FOREIGN KEY(LOC_IDVIDEO) REFERENCES VIDEO(VID_ID)
);

CREATE TABLE SUPPORT (
SUP_ID INT NOT NULL IDENTITY,
SUP_LIBELLE varchar (200) null, 
CONSTRAINT PK_SUPPORT PRIMARY KEY(SUP_ID)
);



CREATE TABLE HISTORIQUE (
HIS_ID INT NOT NULL IDENTITY,
HIS_IDVIDEO INT,
HIS_IDUTILISATEUR INT,
HIS_DATEVISU DATE,
CONSTRAINT PK_HISTORIQUE PRIMARY KEY(HIS_ID),
CONSTRAINT FK_HISTORIQUE_VIDEO FOREIGN KEY(HIS_IDVIDEO) REFERENCES VIDEO(VID_ID),
CONSTRAINT FK_HISTORIQUE_UTILISATEUR FOREIGN KEY(HIS_IDUTILISATEUR) REFERENCES UTILISATEUR(UTI_ID)
);


CREATE TABLE SUPPORTVIDEO (
SUPV_IDVIDEO INT NOT NULL ,
SUPV_IDSUPPORT INT NOT NULL,
SUPV_NOMBRE INT,
SUPV_PRIX INT NOT NULL,
CONSTRAINT FK_SUPPORTVIDEO_VIDEO FOREIGN KEY(SUPV_IDVIDEO) REFERENCES VIDEO(VID_ID),
CONSTRAINT FK_SUPPORTVIDEO_SUPPORT FOREIGN KEY(SUPV_IDSUPPORT) REFERENCES SUPPORT(SUP_ID)
);

