create table Categorie (    
	id integer generated by default as identity (start with 1),
    nom varchar(255),
    catMere_id integer,
    primary key (id));
	
create table Location ( 
   id integer generated by default as identity (start with 1),
   dateLimiteRetour timestamp,
   dateLocation timestamp,
   utilisateur_id integer,
   video_id integer,
   primary key (id));
   
create table Support (
    id integer generated by default as identity (start with 1),
    libelle varchar(255),
    primary key (id));
	
create table Utilisateur ( 
   id integer generated by default as identity (start with 1),
   email varchar(255),
   isAdmin bit not null, 
   login varchar(255),
   mdp varchar(255), 
   nom varchar(255), 
   prenom varchar(255), 
   primary key (id));
   
create table Video ( 
   id integer generated by default as identity (start with 1),
   description varchar(255), 
   image varchar(255), 
   nom varchar(255), 
   categorie_id integer,
   prix float,
   primary key (id));
   
create table Video_Support (
    Video_id integer not null,
    supports_id integer not null,
    primary key (Video_id, supports_id));
	
alter table Categorie     add constraint FKD4C70117AD043F1C     foreign key (catMere_id)     references Categorie;
alter table Historique     add constraint FKEB152FDDA8A0A846     foreign key (video_id)     references Video;
alter table Historique     add constraint FKEB152FDDA613EA46     foreign key (utilisateur_id)     references Utilisateur;
alter table Location     add constraint FK752A03D5A8A0A846     foreign key (video_id)     references Video;
alter table Location     add constraint FK752A03D5A613EA46     foreign key (utilisateur_id)     references Utilisateur;
alter table Video     add constraint FK4ED245BD45E88C6     foreign key (categorie_id)     references Categorie;
alter table Video_Support     add constraint FK9D1757CBA8A0A846     foreign key (Video_id)     references Video;
alter table Video_Support     add constraint FK9D1757CB6BB699F1     foreign key (supports_id)     references Support;